language: node_js
node_js:
  - "10"
dist: trusty
sudo: required

branches:
  only:
  - master

before_script:
  - npm install -g @angular/cli

script:
  - ng build ngx-panel
  - ng build ngx-panel-test --prod --base-href https://kpolaschek.github.io/NGX-Panel/

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  committer_from_gh: true
  local_dir: dist/ngx-panel-test
  on:
    branch: master
